name = "syncbridge"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
no_bundle = true

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
